blank_issues_enabled: true
contact_links:
  - name: FireVision IPTV Discussions
    url: https://github.com/akshaynikhare/FireVisionIPTV/discussions
    about: Ask questions and discuss ideas with the community.
