name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}

      - name: Build with Gradle
        env:
          SIGNING_KEY_STORE: ${{ steps.decode_keystore.outputs.filePath }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: ./gradlew assembleRelease -PversionName=${{ env.VERSION }}

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/FireVisionIPTV-${{ env.VERSION }}.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: app/build/outputs/apk/release/FireVisionIPTV-${{ env.VERSION }}.apk